# Generated by Django 4.2 on 2024-11-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_people_you_may_know'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='people_you_may_know',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
